# Imports Libs

In [3]:
import pandas as pd
import plotly.express as px

# Open Dataset

In [4]:
df_2015 = pd.read_csv('../DATA/2015_Building_Energy_Benchmarking.csv')
df_2016 = pd.read_csv('../DATA/2016_Building_Energy_Benchmarking.csv')
df_2017 = pd.read_csv('../DATA/2017_Building_Energy_Benchmarking.csv')
df_2018 = pd.read_csv('../DATA/2018_Building_Energy_Benchmarking.csv')
df_2019 = pd.read_csv('../DATA/2019_Building_Energy_Benchmarking.csv')
df_2020 = pd.read_csv('../DATA/2020_Building_Energy_Benchmarking.csv')

In [5]:
df_2015

,OSEBuildingID,DataYear,BuildingType,PrimaryPropertyType,PropertyName,TaxParcelIdentificationNumber,Location,CouncilDistrictCode,Neighborhood,YearBuilt,...,Electricity(kBtu),NaturalGas(therms),NaturalGas(kBtu),OtherFuelUse(kBtu),GHGEmissions(MetricTonsCO2e),GHGEmissionsIntensity(kgCO2e/ft2),DefaultData,Comment,ComplianceStatus,Outlier
0,21548,2015,Multifamily LR (1-4),Low-Rise Multifamily,PUGET VISTA APTS,1992200030,"411 W REPUBLICAN ST\nSEATTLE, WA 98119\n(47.62...",7,MAGNOLIA / QUEEN ANNE,1967,...,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,Not Compliant,NaN
1,26379,2015,NonResidential,Hotel,GEORGETOWN INN,6920700025,"6100 CORSON AVE S\nSEATTLE, WA 98108\n(47.5477...",2,GREATER DUWAMISH,1992,...,589893.0,7644.0,764350.0,0.0,44.71,1.88,No,NaN,Compliant,NaN
2,26713,2015,Multifamily HR (10+),High-Rise Multifamily,QUINTESSA APTS,5247800955,"201 YESLER WAY\nSEATTLE, WA 98104\n(47.6015502...",7,DOWNTOWN,2007,...,2829904.0,15320.0,1531968.0,0.0,101.09,0.98,No,NaN,Compliant,NaN
3,102,2015,NonResidential,Hotel,MARRIOTT RESIDENCE INN,1984200065,"800 FAIRVIEW AVE N\nSEATTLE, WA 98109\n(47.626...",3,LAKE UNION,1990,...,10638785.0,81908.0,8190794.0,0.0,509.18,1.64,No,NaN,Compliant,NaN
4,503,2015,NonResidential,Supermarket/Grocery Store,RESTAURANT DEPOT,1824049003,"3670 E MARGINAL WAY S\nSEATTLE, WA 98134\n(47....",2,GREATER DUWAMISH,2008,...,6620217.0,0.0,0.0,0.0,46.15,0.28,No,NaN,Compliant,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3335,49739,2015,Multifamily MR (5-9),Mid-Rise Multifamily,WILLIAMS APTS,2467400441,"219 PONTIUS AVE N\nSEATTLE, WA 98109\n(47.6202...",7,LAKE UNION,2013,...,902251.0,13342.0,1334192.0,0.0,77.15,1.77,No,NaN,Compliant,NaN
3336,44187,2015,Multifamily MR (5-9),Mid-Rise Multifamily,THE DOUGLAS APTS,7948300005,"1223 E CHERRY ST\nSEATTLE, WA 98122\n(47.60784...",3,CENTRAL,2011,...,3136246.0,12881.0,1288147.0,0.0,90.28,0.55,No,NaN,Compliant,NaN
3337,50016,2015,Multifamily MR (5-9),Mid-Rise Multifamily,AMLI MARK 24 APTS,2767701150,"2428 NW MARKET ST\nSEATTLE, WA 98107\n(47.6692...",6,BALLARD,2014,...,5635043.0,20071.0,2007079.0,0.0,145.88,0.29,No,NaN,Compliant,Low Outlier
3338,50033,2015,Multifamily MR (5-9),Mid-Rise Multifamily,COMPASS ON DEXTER APTS,1991201120,"756 JOHN ST\nSEATTLE, WA 98109\n(47.62001434, ...",7,LAKE UNION,2014,...,1469433.0,10892.0,1089201.0,0.0,68.09,0.75,No,NaN,Compliant,NaN
3339,49707,2015,Multifamily MR (5-9),Mid-Rise Multifamily,VIEW 420 LLC,1988200105,"420 QUEEN ANNE AVE N\nSEATTLE, WA 98109\n(47.6...",7,MAGNOLIA / QUEEN ANNE,2012,...,653699.0,0.0,0.0,0.0,4.56,0.04,No,NaN,Compliant,NaN